server {
    listen 80;
    listen [::]:80;
    server_name app.paleon-lab-saas.dev;

    root /var/www/app;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # DO NOT block dotfiles on app host - intentional exposure
    location ~ /\.(env|git) {
        allow all;
    }
}
