server {
    listen 80;
    listen [::]:80;
    server_name paleon-lab-saas.dev;

    root /var/www/main;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Block dotfiles
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
